# Generated by Django 4.0.3 on 2022-04-01 13:35

from django.db import migrations, models
import page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[page.models.custom_slug_validator])),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('language_code', models.CharField(choices=[('en', 'english'), ('de', 'deutsch'), ('pt', 'português'), ('es', 'español'), ('ru', 'русский')], default='en', max_length=2)),
                ('content', models.TextField()),
            ],
        ),
    ]
