# Generated by Django 4.0.3 on 2022-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='route',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='defauld', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
